name: Build Packages
on: [push, pull_request]
jobs:
  Build-Windows-32bit:
    name: Build package for 32-bit x86 Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.3
      - run: msbuild -m "engine/compilers/VisualStudio 2019/Torque 2D.sln" /p:Configuration=Debug /p:Platform=win32
      - run: msbuild -m "engine/compilers/VisualStudio 2019/Torque 2D.sln" /p:Configuration=Release /p:Platform=win32
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Windows_x86_32bit
          path: |
            .
            ! .git/
            ! engine/
  Build-Windows-64bit:
    name: Build package for 64-bit x86 Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.3
      - run: msbuild -m "engine/compilers/VisualStudio 2019/Torque 2D.sln" /p:Configuration=Debug /p:Platform=x64
      - run: msbuild -m "engine/compilers/VisualStudio 2019/Torque 2D.sln" /p:Configuration=Release /p:Platform=x64
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Windows_x86_64bit
          path: |
            .
            ! .git/
            ! engine/
  Build-Linux-32Bit:
    name: Build package for 32-bit x86 Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd engine/compilers/Make-32bit/ && make
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Linux_x86_32bit
          path: |
            .
            ! .git/
            ! engine/
  Build-Linux-64bit:
    name: Build package for 64-bit x86 Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd engine/compilers/Make-64bit/ && make
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Linux_x86_64bit
          path: |
            .
            ! .git/
            ! engine/
